### ISSUE TITLE
Возможные улучшения

### ISSUE THREAD

**Issue by idmitrievsky** [vikian050194/forty#7]
Для запуска из консоли можно использовать https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html, а вообще рекомендую использовать poetry для управления зависимостями и упаковки.

Не понял, нужен ли Time, если есть timedelta.

**Comment by vikian050194** [comment]
Спасибо большое!

1. Time удалил
2. Оба варианта использования скрипта вместе с setuptools освоил и один из них оставил в качестве рабочего варианта

В публичный доступ пока не планирую пакет выкладывать, надо хотя бы основные свои тудушки закрыть
